run:
  modules-download-mode: readonly
  timeout: 2m
  go: "1.23"
  allow-parallel-runners: false

output:
  print-linter-name: true
  formats:
    - format: colored-line-number

linters-settings:
  gofmt:
    simplify: true
  gofumpt:
    module-path: github.com/eng618/go-eng
    extra-rules: true
  gci:
    sections:
      - "standard"
      - "default"
      - prefix(github.com/eng618/go-eng)
  goimports:
    local-prefixes: github.com/eng618/go-eng
  misspell:
    locale: US

linters:
  enable:
    - asciicheck
    - bidichk
    - copyloopvar
    - cyclop
    - decorder
    - errorlint
    - gosec
    - importas
    - gci
    - godot
    - gofmt
    - gofumpt
    - goimports
    - misspell
    - revive
    - whitespace

issues:
  # Disable filter and show all errors defaults to 3
  max-issues-per-linter: 0
