version: '2'
run:
  go: '1.23'
  modules-download-mode: readonly
  allow-parallel-runners: false
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
linters:
  enable:
    - asciicheck
    - bidichk
    - copyloopvar
    - cyclop
    - decorder
    - errorlint
    - godot
    - gosec
    - importas
    - misspell
    - revive
    - whitespace
  settings:
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  # Disable filter and show all errors defaults to 3
  max-issues-per-linter: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/eng618/go-eng)
    gofmt:
      simplify: true
    gofumpt:
      module-path: github.com/eng618/go-eng
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/eng618/go-eng
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
