run:
  modules-download-mode: readonly
  timeout: 5m

output:
  print-linter-name: true
  unique-by-line: true

linters-settings:
  gofmt:
    simplify: true
  gofumpt:
    lang-version: "1.19"
    module-path: github.com/eng618/go-eng
    extra-rules: true
  gci:
    sections:
      - "standard"
      - "default"
      - prefix(github.com/eng618/go-eng)
  goimports:
    local-prefixes: github.com/eng618/go-eng
  misspell:
    locale: US

linters:
  disable:
    - scopelint # deprecated for exportloopref

  enable:
    - asciicheck
    - bidichk
    - cyclop
    - decorder
    - errorlint
    - gosec
    - exportloopref
    - importas
    - gci
    - godot
    - gofmt
    - gofumpt
    - goimports
    - misspell
    - revive
    - whitespace

issues:
  # Disable filter and show all errors defaults to 3
  max-issues-per-linter: 0
