name: build-test-lint
on:
  push:
    tags: [v*]
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.22']
    name: Go ${{ matrix.go }} test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: latest

      - name: Test
        run: go test ./... -cover -race -coverprofile=coverage.out -covermode=atomic

      - name: Build
        run: go build -v ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          # token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
