name: build-test-lint
on:
  push:
    tags: [v*]
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.17", "1.16"]
    name: Go ${{ matrix.go }} test
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

      - name: Test
        run: go test -v ./... -cover -race -coverprofile=coverage.out -covermode=atomic

      - name: Build
        run: go build -v ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
